include $(THEOS)/makefiles/common.mk

TWEAK_NAME = LowerInstall16
LowerInstall16_FILES = LowerInstall.xm
LowerInstall16_FRAMEWORKS = Foundation UIKit
LowerInstall16_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
