include $(THEOS)/makefiles/common.mk

TWEAK_NAME = LowerInstall

LowerInstall_FILES = LowerInstall.xm
LowerInstall_FRAMEWORKS = Foundation UIKit
LowerInstall_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
