include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = LowerInstallSettings
LowerInstallSettings_FILES = LowerInstallSettingsController.m
LowerInstallSettings_INSTALL_PATH = /Library/PreferenceBundles
LowerInstallSettings_FRAMEWORKS = UIKit
LowerInstallSettings_PRIVATE_FRAMEWORKS = Preferences
LowerInstallSettings_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
